# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-31 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_persona_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
    ]
