# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20170525_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
